[config]
# Ép Matugen dùng thuật toán lấy màu chính (không bật interactive)
type = "scheme-tonal-spot" # Hoặc các kiểu: "scheme-expressive", "scheme-vibrant", "scheme-fruit-salad"

[templates.hyprland_colors]
input_path = '~/.config/matugen/templates/colors.lua'
output_path = '~/.config/hypr/config/colors.lua'
