include themes/noctalia.conf

shell /usr/bin/zsh

# Đặt opacity tầm 0.70 để lộ lớp blur Hyprland cực đẹp
background_opacity 0.5

# Cho phép ứng dụng override nếu cần
dynamic_background_opacity yes

# Padding cho khung nhìn cân đối
window_padding_width 10

# Font & UI
font_family      JetBrainsMono Nerd Font
font_size        11.0
hide_window_decorations yes
