color0 #474553
color1 #ffb4ab
color2 #c5c0ff
color3 #c6c1f4
color4 #ffaaf7
color5 #c5c0ff
color6 #c6c1f4
color7 #e5e1eb
color8 #928f9e
color9 #ffb4ab
color10 #c5c0ff
color11 #c6c1f4
color12 #ffaaf7
color13 #c5c0ff
color14 #c6c1f4
color15 #e5e1eb

cursor                #e5e1eb
cursor_text_color     #131319
background            #131319
foreground            #e5e1eb
selection_foreground  #c8c4d5
selection_background  #474553
active_border_color   #c5c0ff
inactive_border_color #474553
url_color             #c5c0ff

active_tab_foreground   #271590
active_tab_background   #c5c0ff
inactive_tab_foreground #c8c4d5
inactive_tab_background #474553
cursor_trail_color      #c8c4d5
