color0 #42484b
color1 #ffb4ab
color2 #a9ccdd
color3 #bbc8d0
color4 #d8bee0
color5 #a9ccdd
color6 #bbc8d0
color7 #e3e2e3
color8 #8c9295
color9 #ffb4ab
color10 #a9ccdd
color11 #bbc8d0
color12 #d8bee0
color13 #a9ccdd
color14 #bbc8d0
color15 #e3e2e3

cursor                #e3e2e3
cursor_text_color     #121415
background            #121415
foreground            #e3e2e3
selection_foreground  #c1c7cb
selection_background  #42484b
active_border_color   #a9ccdd
inactive_border_color #42484b
url_color             #a9ccdd

active_tab_foreground   #103442
active_tab_background   #a9ccdd
inactive_tab_foreground #c1c7cb
inactive_tab_background #42484b
cursor_trail_color      #c1c7cb
