general {
    lock_cmd = pidof hyprlock || hyprlock       # Khóa màn hình
    before_sleep_cmd = loginctl lock-session    # Khóa trước khi sleep
    after_sleep_cmd = hyprctl dispatch dpms on  # Mở lại màn hình khi dậy
}

# 1. Hạ độ sáng màn hình xuống 10% sau 2.5 phút (150 giây)
listener {
    timeout = 150
    on-timeout = brightnessctl -s set 10%
    on-resume = brightnessctl -r
}

# 2. Khóa màn hình sau 5 phút (300 giây)
listener {
    timeout = 300
    on-timeout = loginctl lock-session
}

# 3. Tắt hẳn tín hiệu màn hình (DPMS off) sau 5.5 phút (330 giây)
listener {
    timeout = 330
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}
